// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDci_uhhqm5gzveY-UDMuv3ba2qd3E7Ya8',
    appId: '1:661495323611:web:104186b9f4e149bc3ea5fe',
    messagingSenderId: '661495323611',
    projectId: 'dosecerta-f3bec',
    authDomain: 'dosecerta-f3bec.firebaseapp.com',
    storageBucket: 'dosecerta-f3bec.firebasestorage.app',
    measurementId: 'G-L2955MJ4LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZErNMJ4pa4A3vUX9hufLc7AqRvrKvUY',
    appId: '1:661495323611:android:f04b97c9d0264a183ea5fe',
    messagingSenderId: '661495323611',
    projectId: 'dosecerta-f3bec',
    storageBucket: 'dosecerta-f3bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJtZ-RQY6r1v56lS7Ao7F03yAA29sjD4',
    appId: '1:661495323611:ios:bb8a38644ab0ec123ea5fe',
    messagingSenderId: '661495323611',
    projectId: 'dosecerta-f3bec',
    storageBucket: 'dosecerta-f3bec.firebasestorage.app',
    iosBundleId: 'com.example.doseCerta',
  );

}