// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:dose_certa/Models/Models/lembrete.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LembreteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LembreteAdapter());
  }
}
